/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimbanganRouteImport } from './routes/timbangan'
import { Route as PriceIntelligenceRouteImport } from './routes/price-intelligence'
import { Route as PetugasRouteImport } from './routes/petugas'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LaporanRouteImport } from './routes/laporan'
import { Route as KomoditasRouteImport } from './routes/komoditas'
import { Route as GisMapRouteImport } from './routes/gis-map'
import { Route as ForecastingRouteImport } from './routes/forecasting'
import { Route as DistribusiRouteImport } from './routes/distribusi'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ClusteringRouteImport } from './routes/clustering'
import { Route as AnomalyDetectionRouteImport } from './routes/anomaly-detection'
import { Route as AktivitasPetugasRouteImport } from './routes/aktivitas-petugas'
import { Route as AiCenterRouteImport } from './routes/ai-center'
import { Route as AiAnalyticsRouteImport } from './routes/ai-analytics'
import { Route as IndexRouteImport } from './routes/index'

const TimbanganRoute = TimbanganRouteImport.update({
  id: '/timbangan',
  path: '/timbangan',
  getParentRoute: () => rootRouteImport,
} as any)
const PriceIntelligenceRoute = PriceIntelligenceRouteImport.update({
  id: '/price-intelligence',
  path: '/price-intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const PetugasRoute = PetugasRouteImport.update({
  id: '/petugas',
  path: '/petugas',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LaporanRoute = LaporanRouteImport.update({
  id: '/laporan',
  path: '/laporan',
  getParentRoute: () => rootRouteImport,
} as any)
const KomoditasRoute = KomoditasRouteImport.update({
  id: '/komoditas',
  path: '/komoditas',
  getParentRoute: () => rootRouteImport,
} as any)
const GisMapRoute = GisMapRouteImport.update({
  id: '/gis-map',
  path: '/gis-map',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastingRoute = ForecastingRouteImport.update({
  id: '/forecasting',
  path: '/forecasting',
  getParentRoute: () => rootRouteImport,
} as any)
const DistribusiRoute = DistribusiRouteImport.update({
  id: '/distribusi',
  path: '/distribusi',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ClusteringRoute = ClusteringRouteImport.update({
  id: '/clustering',
  path: '/clustering',
  getParentRoute: () => rootRouteImport,
} as any)
const AnomalyDetectionRoute = AnomalyDetectionRouteImport.update({
  id: '/anomaly-detection',
  path: '/anomaly-detection',
  getParentRoute: () => rootRouteImport,
} as any)
const AktivitasPetugasRoute = AktivitasPetugasRouteImport.update({
  id: '/aktivitas-petugas',
  path: '/aktivitas-petugas',
  getParentRoute: () => rootRouteImport,
} as any)
const AiCenterRoute = AiCenterRouteImport.update({
  id: '/ai-center',
  path: '/ai-center',
  getParentRoute: () => rootRouteImport,
} as any)
const AiAnalyticsRoute = AiAnalyticsRouteImport.update({
  id: '/ai-analytics',
  path: '/ai-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-analytics': typeof AiAnalyticsRoute
  '/ai-center': typeof AiCenterRoute
  '/aktivitas-petugas': typeof AktivitasPetugasRoute
  '/anomaly-detection': typeof AnomalyDetectionRoute
  '/clustering': typeof ClusteringRoute
  '/dashboard': typeof DashboardRoute
  '/distribusi': typeof DistribusiRoute
  '/forecasting': typeof ForecastingRoute
  '/gis-map': typeof GisMapRoute
  '/komoditas': typeof KomoditasRoute
  '/laporan': typeof LaporanRoute
  '/login': typeof LoginRoute
  '/petugas': typeof PetugasRoute
  '/price-intelligence': typeof PriceIntelligenceRoute
  '/timbangan': typeof TimbanganRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-analytics': typeof AiAnalyticsRoute
  '/ai-center': typeof AiCenterRoute
  '/aktivitas-petugas': typeof AktivitasPetugasRoute
  '/anomaly-detection': typeof AnomalyDetectionRoute
  '/clustering': typeof ClusteringRoute
  '/dashboard': typeof DashboardRoute
  '/distribusi': typeof DistribusiRoute
  '/forecasting': typeof ForecastingRoute
  '/gis-map': typeof GisMapRoute
  '/komoditas': typeof KomoditasRoute
  '/laporan': typeof LaporanRoute
  '/login': typeof LoginRoute
  '/petugas': typeof PetugasRoute
  '/price-intelligence': typeof PriceIntelligenceRoute
  '/timbangan': typeof TimbanganRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-analytics': typeof AiAnalyticsRoute
  '/ai-center': typeof AiCenterRoute
  '/aktivitas-petugas': typeof AktivitasPetugasRoute
  '/anomaly-detection': typeof AnomalyDetectionRoute
  '/clustering': typeof ClusteringRoute
  '/dashboard': typeof DashboardRoute
  '/distribusi': typeof DistribusiRoute
  '/forecasting': typeof ForecastingRoute
  '/gis-map': typeof GisMapRoute
  '/komoditas': typeof KomoditasRoute
  '/laporan': typeof LaporanRoute
  '/login': typeof LoginRoute
  '/petugas': typeof PetugasRoute
  '/price-intelligence': typeof PriceIntelligenceRoute
  '/timbangan': typeof TimbanganRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-analytics'
    | '/ai-center'
    | '/aktivitas-petugas'
    | '/anomaly-detection'
    | '/clustering'
    | '/dashboard'
    | '/distribusi'
    | '/forecasting'
    | '/gis-map'
    | '/komoditas'
    | '/laporan'
    | '/login'
    | '/petugas'
    | '/price-intelligence'
    | '/timbangan'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-analytics'
    | '/ai-center'
    | '/aktivitas-petugas'
    | '/anomaly-detection'
    | '/clustering'
    | '/dashboard'
    | '/distribusi'
    | '/forecasting'
    | '/gis-map'
    | '/komoditas'
    | '/laporan'
    | '/login'
    | '/petugas'
    | '/price-intelligence'
    | '/timbangan'
  id:
    | '__root__'
    | '/'
    | '/ai-analytics'
    | '/ai-center'
    | '/aktivitas-petugas'
    | '/anomaly-detection'
    | '/clustering'
    | '/dashboard'
    | '/distribusi'
    | '/forecasting'
    | '/gis-map'
    | '/komoditas'
    | '/laporan'
    | '/login'
    | '/petugas'
    | '/price-intelligence'
    | '/timbangan'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiAnalyticsRoute: typeof AiAnalyticsRoute
  AiCenterRoute: typeof AiCenterRoute
  AktivitasPetugasRoute: typeof AktivitasPetugasRoute
  AnomalyDetectionRoute: typeof AnomalyDetectionRoute
  ClusteringRoute: typeof ClusteringRoute
  DashboardRoute: typeof DashboardRoute
  DistribusiRoute: typeof DistribusiRoute
  ForecastingRoute: typeof ForecastingRoute
  GisMapRoute: typeof GisMapRoute
  KomoditasRoute: typeof KomoditasRoute
  LaporanRoute: typeof LaporanRoute
  LoginRoute: typeof LoginRoute
  PetugasRoute: typeof PetugasRoute
  PriceIntelligenceRoute: typeof PriceIntelligenceRoute
  TimbanganRoute: typeof TimbanganRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timbangan': {
      id: '/timbangan'
      path: '/timbangan'
      fullPath: '/timbangan'
      preLoaderRoute: typeof TimbanganRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/price-intelligence': {
      id: '/price-intelligence'
      path: '/price-intelligence'
      fullPath: '/price-intelligence'
      preLoaderRoute: typeof PriceIntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/petugas': {
      id: '/petugas'
      path: '/petugas'
      fullPath: '/petugas'
      preLoaderRoute: typeof PetugasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/laporan': {
      id: '/laporan'
      path: '/laporan'
      fullPath: '/laporan'
      preLoaderRoute: typeof LaporanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/komoditas': {
      id: '/komoditas'
      path: '/komoditas'
      fullPath: '/komoditas'
      preLoaderRoute: typeof KomoditasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gis-map': {
      id: '/gis-map'
      path: '/gis-map'
      fullPath: '/gis-map'
      preLoaderRoute: typeof GisMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecasting': {
      id: '/forecasting'
      path: '/forecasting'
      fullPath: '/forecasting'
      preLoaderRoute: typeof ForecastingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/distribusi': {
      id: '/distribusi'
      path: '/distribusi'
      fullPath: '/distribusi'
      preLoaderRoute: typeof DistribusiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clustering': {
      id: '/clustering'
      path: '/clustering'
      fullPath: '/clustering'
      preLoaderRoute: typeof ClusteringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anomaly-detection': {
      id: '/anomaly-detection'
      path: '/anomaly-detection'
      fullPath: '/anomaly-detection'
      preLoaderRoute: typeof AnomalyDetectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aktivitas-petugas': {
      id: '/aktivitas-petugas'
      path: '/aktivitas-petugas'
      fullPath: '/aktivitas-petugas'
      preLoaderRoute: typeof AktivitasPetugasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-center': {
      id: '/ai-center'
      path: '/ai-center'
      fullPath: '/ai-center'
      preLoaderRoute: typeof AiCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-analytics': {
      id: '/ai-analytics'
      path: '/ai-analytics'
      fullPath: '/ai-analytics'
      preLoaderRoute: typeof AiAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiAnalyticsRoute: AiAnalyticsRoute,
  AiCenterRoute: AiCenterRoute,
  AktivitasPetugasRoute: AktivitasPetugasRoute,
  AnomalyDetectionRoute: AnomalyDetectionRoute,
  ClusteringRoute: ClusteringRoute,
  DashboardRoute: DashboardRoute,
  DistribusiRoute: DistribusiRoute,
  ForecastingRoute: ForecastingRoute,
  GisMapRoute: GisMapRoute,
  KomoditasRoute: KomoditasRoute,
  LaporanRoute: LaporanRoute,
  LoginRoute: LoginRoute,
  PetugasRoute: PetugasRoute,
  PriceIntelligenceRoute: PriceIntelligenceRoute,
  TimbanganRoute: TimbanganRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
